[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
(?x)(
    \.git
  | \.venv
  | env
  | __pycache__
  | pyproject.toml
)
'''

[tool.pylint."MAIN"]
ignore = ["env", ".venv", "__pycache__", "pyproject.toml"]

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-many-locals",
    "too-few-public-methods",
    "too-many-instance-attributes"
]

[tool.pylint."FORMAT"]
max-line-length = 100

[tool.isort]
profile = "black"
line_length = 100
skip = ["env", ".venv", "__pycache__"]

